"""Regression tests for ``_replace_membership_rows`` DELETE predicate.

These tests pin the fix for the bug where monthly sync (narrow window) was deleting
historical anchor rows (effective_date=2016-01-01, end_date=NULL) generated by earlier
full backfills. The symptom was ``get_universe_pit(2020-09-15)`` returning ~50 members
instead of ~500 a few days after a full Wikipedia-based backfill.
"""

from __future__ import annotations

from datetime import date

import pytest
import sqlalchemy as sa
from sqlalchemy.pool import StaticPool

import src.universe.builder as builder_module
from src.data.db.models import Base, UniverseMembership


def _engine():
    engine = sa.create_engine(
        "sqlite+pysqlite:///:memory:",
        future=True,
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine, tables=[UniverseMembership.__table__], checkfirst=True)
    return engine


def _install_session_factory(monkeypatch: pytest.MonkeyPatch):
    engine = _engine()
    session_factory = sa.orm.sessionmaker(bind=engine, expire_on_commit=False)
    monkeypatch.setattr(builder_module, "get_session_factory", lambda: session_factory)
    return session_factory


def _seed_historical_anchors(session_factory) -> None:
    """Prior full backfill populated these; monthly sync must NOT delete them."""
    with session_factory() as session:
        session.add_all(
            [
                # AAPL: always-in anchor (end_date NULL) — this is what the buggy DELETE wiped
                UniverseMembership(
                    ticker="AAPL",
                    index_name="SP500",
                    effective_date=date(2016, 1, 1),
                    end_date=None,
                    reason="historical_backfill_anchor",
                ),
                # ATVI: exited SP500 in 2023 (survived buggy DELETE because end_date set) — kept
                # as a control to confirm the test setup
                UniverseMembership(
                    ticker="ATVI",
                    index_name="SP500",
                    effective_date=date(2016, 1, 1),
                    end_date=date(2023, 10, 18),
                    reason="historical_backfill_anchor",
                ),
            ],
        )
        session.commit()


def test_monthly_sync_preserves_historical_anchors(monkeypatch: pytest.MonkeyPatch) -> None:
    """Simulate `ensure_monthly_universe_membership` calling `_replace_membership_rows`
    with a narrow (2026-04-01, 2026-04-21) window after a full backfill has already
    populated 2016-01-01 anchors. Anchors MUST survive.
    """
    session_factory = _install_session_factory(monkeypatch)
    _seed_historical_anchors(session_factory)

    # Narrow monthly-sync invocation: insert 1 new row for AAPL at 2026-04-01 (current month anchor)
    new_rows = [
        {
            "ticker": "AAPL",
            "index_name": "SP500",
            "effective_date": date(2026, 4, 1),
            "end_date": None,
            "reason": "monthly_sync",
        },
    ]
    builder_module._replace_membership_rows(
        new_rows,
        start_date=date(2026, 4, 1),
        end_date=date(2026, 4, 21),
        index_name="SP500",
    )

    with session_factory() as session:
        rows = (
            session.execute(
                sa.select(UniverseMembership).where(UniverseMembership.ticker == "AAPL")
                .order_by(UniverseMembership.effective_date),
            )
            .scalars()
            .all()
        )
    # AAPL should now have TWO rows: 2016-01-01 anchor (preserved as history
    # but closed) + 2026-04-01 monthly sync as the only active row.
    assert len(rows) == 2, f"expected 2 AAPL rows (anchor + monthly), got {[r.effective_date for r in rows]}"
    assert rows[0].effective_date == date(2016, 1, 1)
    assert rows[0].end_date == date(2026, 4, 1)
    assert rows[0].reason == "historical_backfill_anchor"
    assert rows[1].effective_date == date(2026, 4, 1)
    assert rows[1].end_date is None
    assert rows[1].reason == "monthly_sync"

    # ATVI exit row also preserved (control)
    with session_factory() as session:
        atvi = (
            session.execute(sa.select(UniverseMembership).where(UniverseMembership.ticker == "ATVI"))
            .scalars()
            .all()
        )
    assert len(atvi) == 1
    assert atvi[0].end_date == date(2023, 10, 18)


def test_full_backfill_replaces_rows_in_window_cleanly(monkeypatch: pytest.MonkeyPatch) -> None:
    """Full backfill (start=2016-01-01, end=today) must wipe stale 2016 rows before inserting
    a fresh set — old rows with effective_date ∈ window get replaced, not duplicated.
    """
    session_factory = _install_session_factory(monkeypatch)
    # Seed an old incorrect anchor that the full backfill should clean up
    with session_factory() as session:
        session.add(
            UniverseMembership(
                ticker="AAPL",
                index_name="SP500",
                effective_date=date(2016, 1, 1),
                end_date=None,
                reason="stale_anchor",
            ),
        )
        session.commit()

    # Full backfill replaces with fresh anchor + change events
    new_rows = [
        {
            "ticker": "AAPL",
            "index_name": "SP500",
            "effective_date": date(2016, 1, 1),
            "end_date": None,
            "reason": "full_backfill",
        },
        {
            "ticker": "ATVI",
            "index_name": "SP500",
            "effective_date": date(2016, 1, 1),
            "end_date": date(2023, 10, 18),
            "reason": "full_backfill",
        },
    ]
    builder_module._replace_membership_rows(
        new_rows,
        start_date=date(2016, 1, 1),
        end_date=date(2026, 4, 21),
        index_name="SP500",
    )

    with session_factory() as session:
        rows = session.execute(sa.select(UniverseMembership)).scalars().all()
    assert len(rows) == 2
    aapl = next(r for r in rows if r.ticker == "AAPL")
    assert aapl.reason == "full_backfill"  # stale_anchor was replaced


def test_targeted_historical_refill_preserves_earlier_anchors(monkeypatch: pytest.MonkeyPatch) -> None:
    """Targeted refill of just the 2020-2022 sub-window should NOT touch pre-2020 anchors."""
    session_factory = _install_session_factory(monkeypatch)
    with session_factory() as session:
        session.add_all(
            [
                UniverseMembership(
                    ticker="AAPL", index_name="SP500",
                    effective_date=date(2016, 1, 1), end_date=None, reason="anchor_2016",
                ),
                UniverseMembership(
                    ticker="BBB", index_name="SP500",
                    effective_date=date(2018, 6, 5), end_date=None, reason="anchor_2018",
                ),
            ],
        )
        session.commit()

    # Refill only 2020-2022 — no rows actually fall here, but verify pre-window survives
    builder_module._replace_membership_rows(
        [],
        start_date=date(2020, 1, 1),
        end_date=date(2022, 12, 31),
        index_name="SP500",
    )
    with session_factory() as session:
        rows = session.execute(sa.select(UniverseMembership).order_by(UniverseMembership.effective_date)).scalars().all()
    assert len(rows) == 2
    assert rows[0].ticker == "AAPL" and rows[0].effective_date == date(2016, 1, 1)
    assert rows[1].ticker == "BBB" and rows[1].effective_date == date(2018, 6, 5)
