import React from 'react';
import GlassCard from '../components/ui/GlassCard';

const Signals: React.FC = () => {
  return (
    <div className="space-y-6">
      <header className="mb-8">
        <h1 className="text-4xl font-extrabold tracking-tight text-on-surface">Alpha Stream</h1>
        <p className="text-on-surface-variant">Real-time proprietary signals generated by our ensemble models.</p>
      </header>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {[1, 2, 3, 4, 5, 6].map((i) => (
          <GlassCard key={i} className="h-48 flex items-center justify-center">
            <p className="text-on-surface-variant font-bold uppercase tracking-widest">Signal Card {i} - Coming Soon</p>
          </GlassCard>
        ))}
      </div>
    </div>
  );
};

export default Signals;
